
import type { Job } from './job';
export const mockJobs: Job[] = [
    {
        id: 1,
        jobName: "Senior Frontend Developer",
        positionName: "Senior Developer",
        functionalArea: "IT Software - Application Programming",
        functionalRole: "Software Developer",
        skills: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
        avgExp: 5,
        avgWage: 18,
        gender: "Any",
        highestQualification: "Bachelor's Degree",
        state: "Maharashtra",
        district: "Pune",
        description: "We are looking for an experienced Frontend Developer to join our team. The ideal candidate will have strong proficiency in React and a passion for building beautiful and performant user interfaces.",
        matchScore: 95,
    },
    {
        id: 2,
        jobName: "Data Scientist",
        positionName: "Data Scientist",
        functionalArea: "Analytics & Business Intelligence",
        functionalRole: "Data Scientist",
        skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
        avgExp: 4,
        avgWage: 22,
        gender: "Any",
        highestQualification: "Master's Degree",
        state: "Karnataka",
        district: "Bengaluru",
        description: "Join our data science team to build predictive models and solve complex business problems. Experience with deep learning frameworks is a plus.",
        matchScore: 92,
    },
    {
        id: 3,
        jobName: "Product Manager",
        positionName: "Manager",
        functionalArea: "Product Management",
        functionalRole: "Product Manager",
        skills: ["Agile", "Roadmap Planning", "User Research", "JIRA"],
        avgExp: 7,
        avgWage: 25,
        gender: "Any",
        highestQualification: "MBA",
        state: "Telangana",
        district: "Hyderabad",
        description: "We are seeking a strategic Product Manager to own the product lifecycle from conception to launch. You will work cross-functionally with engineering, design, and marketing teams.",
        matchScore: 88,
    },
    {
        id: 4,
        jobName: "UX/UI Designer",
        positionName: "Designer",
        functionalArea: "Design, Creative, User Experience",
        functionalRole: "UX Designer",
        skills: ["Figma", "Adobe XD", "Prototyping", "Wireframing"],
        avgExp: 3,
        avgWage: 12,
        gender: "Any",
        highestQualification: "Bachelor's Degree",
        state: "Maharashtra",
        district: "Mumbai",
        description: "Create intuitive and visually appealing user experiences for our web and mobile applications. A strong portfolio is required.",
        matchScore: 85,
    },
    {
        id: 5,
        jobName: "Backend Developer (Java)",
        positionName: "Software Engineer",
        functionalArea: "IT Software - Application Programming",
        functionalRole: "Software Developer",
        skills: ["Java", "Spring Boot", "Microservices", "SQL"],
        avgExp: 4,
        avgWage: 16,
        gender: "Any",
        highestQualification: "Bachelor's Degree",
        state: "Karnataka",
        district: "Bengaluru",
        description: "Develop and maintain scalable backend services using Java and Spring Boot. Experience with cloud platforms like AWS is highly desirable.",
        matchScore: 82,
    },
    {
        id: 6,
        jobName: "DevOps Engineer",
        positionName: "Engineer",
        functionalArea: "IT Software - System Programming",
        functionalRole: "DevOps Engineer",
        skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
        avgExp: 5,
        avgWage: 20,
        gender: "Any",
        highestQualification: "Bachelor's Degree",
        state: "Maharashtra",
        district: "Pune",
        description: "Manage and improve our cloud infrastructure and CI/CD pipelines. Strong scripting skills and experience with infrastructure as code are essential.",
        matchScore: 78,
    },
];